spring:
  application:
    name: springcicddemo2

server:
  port: 7777

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
